version: '3'

services:
  db:
   image: postgres:latest
   container_name: postgres
   environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'root'
    POSTGRES_DB: 'financeirosinmedrn'
   ports:
    - "5432:5432" 
   volumes:
   - .\postgres-data:/var/lib/postgresql/data
